# Application
spring:
  application:
    name: api-gateway

# Spring Cloud Api Gateway
  cloud:
    gateway:
      routes:
        # product-service
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product-service/**
          filters:
            - StripPrefix=1
        # order-service
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order-service/**
          filters:
            - StripPrefix=1
        # inventory-service
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/inventory-service/**
          filters:
            - StripPrefix=1

# Application
server:
  port: 8080

# Spring Cloud Eureka client
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka